site_name: Custom Import Rules

docs_dir: docs

theme:
  name: "material"
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  features:
    #      - navigation.tabs
    - navigation.indexes
    - navigation.instant

repo_name: RodrigoGonzalez/flake8-custom-import-rules
repo_url: https://github.com/RodrigoGonzalez/flake8-custom-import-rules

plugins:
  - search:
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          rendering:
            show_signature_annotations: true
            show_source: true
          paths: [src/flake8_custom_import_rules/]

watch:
  - src/flake8_custom_import_rules

nav:
  - Introduction: "index.md"
  - API Documentation: "api_docs.md"
  - glossary.md
  - Dynamic Imports Explained: "dynamic_imports.md"
  - Changelog: "changelog.md"
  - License: "license.md"

markdown_extensions:
  - pymdownx.snippets:
      check_paths: true
  - toc:
      baselevel: 2

# to navigate with `/site` content correctly
use_directory_urls: false
