[tool.poetry]
name = "flake8_custom_import_rules"
version = "0.8.8"
description = "A Flake8 plugin that enforces custom import rules, allowing users to define and maintain clean and consistent import organization across their Python projects."
readme = "README.rst"
authors = ["Rodrigo Gonzalez <flake8.custom.import.rules@gmail.com>"]
license = "MIT"

#packages = [
#    {include = "flake8_custom_import_rules", from = "build/lib"}
#]

[tool.poetry.dependencies]
python = ">=3.9,<=3.12"
flake8 = "^6.0.0"
importlib-metadata = { version = "^4.0", python = "<3.8" }
pylama = "^8.4.1"
stdlib-list = { version = "^0.9.0", python = "<3.10" }
pycodestyle = "^2.10.0"
attrs = "^23.1.0"


[tool.poetry.group.dev.dependencies]
astpretty = "^3.0.0"
ipython = "^8.12.0"
commitizen = "^3.0.1"
pre-commit = "^3.2.2"
isort = "^5.12.0"
black = "^23.3.0"
autoflake = "^2.1.1"
mypy = "^1.2.0"
lxml = "^4.9.3"
cython = "^3.0.0"


[tool.poetry.group.test.dependencies]
pytest = "^7.4.0"
pytest-cov = "^4.1.0"
toml = "^0.10.2"
tox = "^4.6.4"
tox-gh-actions = "^3.1.3"
coverage = { version = "^7.2.7",  extras = ["toml"] }
covdefaults = "^2.3.0"



[tool.commitizen]
name = "cz_conventional_commits"
version = "0.8.8"
tag_format = "v$version"
version_type = "semver"
update_changelog_on_bump = true
major_version_zero = true
version_files = [
    "pyproject.toml:version",
    "setup.cfg:version",
    "src/flake8_custom_import_rules/__init__.py:__version__",
]
changelog_file = "CHANGELOG.md"

[tool.isort]
profile = "black"
skip_glob = ["docs", "example_repos"]
line_length = 100
multi_line_output = 4
force_single_line = true
src_paths = ["src", "tests", "scripts"]
sections = ["FUTURE", "STDLIB", "THIRDPARTY", "FIRSTPARTY", "LOCALFOLDER"]
known_first_party = ["flake8_custom_import_rules", "my_base_module"]
known_third_party = ["flake8"]

[tool.black]
line-length = 100
target-version = ["py39", "py310", "py311"]
include = '\.pyi?$'
exclude = '''
    /(
        \.git
      | \.mypy_cache
      | \.mypy_html_report
      | \.venv
      | _build
      | build
      | dist
      | docs
      | example_repos
    )/
'''

[tool.mypy]
# output
show_error_codes = true
show_column_numbers = true
show_error_context = true
show_traceback = true
# 3rd party import
ignore_missing_imports = true
# dynamic typing
disallow_any_unimported = false
disallow_any_expr = false
disallow_any_decorated = false
disallow_any_explicit = false
disallow_any_generics = false
disallow_subclassing_any = false
# platform
python_version = "3.10"
# untyped
disallow_untyped_calls = true
disallow_untyped_defs = true
disallow_incomplete_defs = true
disallow_untyped_decorators = true
# None and Optional
no_implicit_optional = true
# strictness
explicit_package_bases = true
# Warnings
warn_return_any = false
warn_unreachable = true
# Misc
pretty = true
exclude = [
    "example_repos",
    "tests",
]

[tool.coverage.run]
plugins = ["covdefaults"]
omit = ["flake8_custom_import_rules/example_repos/*"]

[tool.poetry.scripts]
CIR = "flake8_custom_import_rules.flake8_linter:Plugin"

[build-system]
#requires = ["poetry-core"]
#build-backend = "poetry.core.masonry.api"
# from https://setuptools.pypa.io/en/latest/userguide/pyproject_config.html
requires = ["setuptools", "setuptools-scm"]
build-backend = "setuptools.build_meta"
