[tool.poetry]
name = "flake8_custom_import"
version = "0.0.1"
description = "A Flake8 plugin that enforces custom import rules, allowing users to define and maintain clean and consistent import organization across their Python projects."
authors = ["Rodrigo Gonzalez <r@rodrigo-gonzalez.com>"]
license = "MIT"
readme = "README.md"
packages = [
    {include = "flake8_custom_import_rules", from = "src"}
]

[tool.poetry.dependencies]
python = ">=3.8.1,<3.12"
flake8 = "^6.0.0"
flake8-import-order = "^0.18.1"
importlib-metadata = { version = "^4.0", python = "<3.8" }
pylama = "^8.4.1"

[tool.poetry.group.dev.dependencies]
astpretty = "^3.0.0"
ipython = "^8.12.0"
pytest = "^7.3.1"
commitizen = "^3.0.1"
pre-commit = "^3.2.2"

[tool.commitizen]
name = "cz_conventional_commits"
tag_format = "$version"
version_type = "semver"
version_provider = "poetry"
update_changelog_on_bump = true
major_version_zero = true
version_files = [
    "pyproject.toml:version",
    "src/flake8_custom_import_rules/__init__.py:__version__",
]
update_changelog_on_bump = true
changelog_file = "CHANGELOG.md"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
