blank_issues_enabled: true
contact_links:
  - name: Discussions
    url: https://github.com/RodrigoGonzalez/flake8-custom-import-rules/discussions/new
    about: Ask questions and discuss with other community members
  - name: Blank issue
    url: https://github.com/RodrigoGonzalez/flake8-custom-import-rules/issues/new
    about: Please note that Github Discussions should be used in most cases instead
