name: Feature request
description: Suggest a new error code, custom import rule, enhancement, etc.
labels: ['New Feature', 'Needs Triage']

body:
- type: textarea
  attributes:
    label: Describe the workflow you want to enable
  validations:
    required: true
- type: textarea
  attributes:
    label: Describe your proposed solution
  validations:
    required: true
- type: textarea
  attributes:
    label: Describe alternatives you've considered, if relevant
- type: textarea
  attributes:
    label: Additional context
