name: Publish documentation

on:
  push:
    tags:
      - 'v*'

jobs:
  publish-documentation:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v7
      with:
        token: '${{ secrets.PERSONAL_ACCESS_TOKEN }}'
        fetch-depth: 0

    - name: Install uv and set the Python version
      uses: astral-sh/setup-uv@bec219d24cd3e171d82865faccec33120bb574f4 # v10.1.0
      with:
        version: "0.12.17"
        python-version: "3.11"
        enable-cache: true

    - name: Install dependencies
      run: uv sync --locked --no-default-groups --group docs

    - name: Build docs
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: uv run --locked --no-default-groups --group docs mkdocs build
    - name: Push doc to Github Page
      uses: peaceiris/actions-gh-pages@v4
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        PERSONAL_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        PUBLISH_BRANCH: gh-pages
        PUBLISH_DIR: ./site
