name: Publish documentation

on:
  push:
    tags:
      - 'v*'

jobs:
  publish-documentation:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        token: '${{ secrets.PERSONAL_ACCESS_TOKEN }}'
        fetch-depth: 0
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install poetry
      run: pipx install poetry==1.5.1

    - name: Install dependencies
      run: |
        poetry install --only main,docs

    - name: Build docs
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        poetry run mkdocs build
    - name: Push doc to Github Page
      uses: peaceiris/actions-gh-pages@v3
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        PERSONAL_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        PUBLISH_BRANCH: gh-pages
        PUBLISH_DIR: ./site
