name: Publish documentation

on:
  push:
    branches:
      - main
    paths:
      - 'docs/**'
      - 'mkdocs.yml'
      - 'CHANGELOG.md'
      - 'LICENSE'
      - 'pyproject.toml'
      - 'uv.lock'
      - '.github/workflows/docspublish.yml'

  workflow_dispatch:

concurrency:
  group: documentation-deployment
  cancel-in-progress: true

jobs:
  publish-documentation:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v7
      with:
        token: '${{ secrets.PERSONAL_ACCESS_TOKEN }}'
        fetch-depth: 0

    - name: Install uv and set the Python version
      uses: astral-sh/setup-uv@c771a70e6277c0a99b617c7a806ffedaca235ff9 # v9.0.0
      with:
        version: "0.12.17"
        python-version: "3.11"
        enable-cache: true

    - name: Install dependencies
      run: uv sync --locked --no-default-groups --group docs

    - name: Build docs
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: uv run --locked --no-default-groups --group docs mkdocs build
    - name: Push doc to Github Page
      uses: peaceiris/actions-gh-pages@v4
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        PERSONAL_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        PUBLISH_BRANCH: gh-pages
        PUBLISH_DIR: ./site
